### ISSUE TITLE
Exception using 'Contains' on text column

### ISSUE THREAD

**Issue by dustinsaunders** [SveNord/Sve-Blazor-DataTable#4]
When using the filter function for a string the Contains filter option throws an exception breaking the connection.

```System.InvalidOperationException: The 'Like' method is not supported because the query has switched to client-evaluation. This usually happens when the arguments to the method cannot be translated to server. Rewrite the query to avoid client evaluation of arguments so that method can be translated to server.
   at Microsoft.EntityFrameworkCore.DbFunctionsExtensions.LikeCore(String matchExpression, String pattern, String escapeCharacter)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Sve.Blazor.DataTable.Components.DataTable`1.PerformClientSideDataManipulations()
   at Sve.Blazor.DataTable.Components.DataTable`1.ApplyFilters()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)```

**Comment by SveNord** [comment]
Hey, first of all sorry for the inactivity. Do you still have this problem and if so you can you give me some more information on how you are getting this issue?
